#!/usr/bin/env python3
"""
plot_ampar_rmsd.py

Description:
This script reads the RMSD time-series data generated by `calc_ampar_rmsd_box.py`
and generates a combined, publication-quality plot using matplotlib and seaborn.

It allows you to overlay multiple systems (e.g., Wild Type vs. Mutants) to compare
their structural stability over the simulation time.

Outputs:
A high-resolution PNG/PDF figure of the combined RMSD trajectories.
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def main():
    # 1. Setup Argument Parsing
    parser = argparse.ArgumentParser(description="Plot Combined AMPAR Backbone RMSD")
    parser.add_argument("--prefixes", nargs='+', required=True, 
                        help="List of system prefixes to plot (e.g., Q586_1 Q586E_0 wild_type)")
    parser.add_argument("--out_file", default="RMSD_Combined_Plot.png", 
                        help="Output filename for the plot (default: RMSD_Combined_Plot.png)")
    parser.add_argument("--dt", type=float, default=0.1, 
                        help="Time step between frames in nanoseconds (default: 0.1 ns)")
    args = parser.parse_args()

    print(f"Preparing to plot RMSD for systems: {args.prefixes}")

    # Set standard publication-quality aesthetics
    sns.set_theme(style="ticks", context="paper", font_scale=1.2)
    plt.figure(figsize=(8, 5))

    # Define a consistent color palette for multiple lines
    colors = sns.color_palette("husl", len(args.prefixes))

    data_found = False

    # 2. Read and Plot Data
    for idx, prefix in enumerate(args.prefixes):
        input_file = f"RMSD.{prefix}.txt"
        
        if not os.path.exists(input_file):
            print(f"Warning: Could not find {input_file}. Skipping...")
            continue
            
        print(f"Loading {input_file}...")
        
        # Read the data using sep=r'\s+' to avoid future pandas warnings
        try:
            df = pd.read_csv(input_file, sep=r'\s+', header=0)
            
            # Extract columns (Frame Index -> Time in ns, RMSD in Angstroms)
            time_ns = df.iloc[:, 0] * args.dt
            rmsd_A = df.iloc[:, 1]
            
            # Plot the raw data with slight transparency
            plt.plot(time_ns, rmsd_A, label=prefix, color=colors[idx], alpha=0.8, linewidth=1.5)
            data_found = True
            
        except Exception as e:
            print(f"Error processing {input_file}: {e}")

    # 3. Finalize and Save the Plot
    if data_found:
        plt.title("AMPAR Backbone Structural Stability", weight='bold')
        plt.xlabel("Simulation Time (ns)", weight='bold')
        plt.ylabel(r"Backbone RMSD ($\AA$)", weight='bold')
        
        # Format axes
        sns.despine()
        plt.legend(title="System", frameon=False, loc="best")
        plt.tight_layout()

        # Save figure
        print(f"Saving high-resolution plot to {args.out_file}...")
        plt.savefig(args.out_file, dpi=300, bbox_inches="tight")
        print("Plot generation complete!")
    else:
        print("Error: No valid data files were found to plot.")

if __name__ == "__main__":
    main()